import React from "react";


const MovingText = () => {

    return (
        <>
            <div className="moving-text-container">
                <div className="scrolling-text">
                Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education •
                Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education •
                Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education •
                Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education •
                Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education •
                Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education •
                Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education •
                Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education • Proximamente en Top Education •
                </div>
            </div>
        </>
    );
};

export default MovingText